name: App deploy to EKS
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Running unit tests with pytest
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -q

      - name: Running coverage tests with pytest
        run: |
          pytest --cov=src --cov-report=term-missing tests/

      # - name: Running check components without tests
      #   run: |
      #     # Adicione um comando para verificar componentes sem testes, por exemplo, se você tiver algo semelhante
      #     python -m unittest discover -s checks  # Exemplo de comando para verificar sem testes